---
- name: install mysql packages
  with_items: "{{ mysql_packages }}"
  package:
    name: "{{ item.name }}"
  notify:
    - restart mysql

- name: configure mysql
  template:
    src: server.cnf.j2
    dest: /usr/local/etc/mysql/conf.d/server.cnf
  notify:
    - restart mysql

- name: enable mysql
  template:
    src: mysql.j2
    dest: /etc/rc.conf.d/mysql
  notify:
    - restart mysql

- name: start mysql
  service:
    name: mysql-server
    state: started
    enabled: yes
    
- name: create mysql user for all hosts
  mysql_user:
    name: "{{ mysql_user }}"
    host: "{{ mysql_host }}"
    password: "{{ mysql_password }}"
    priv: "*.*:ALL,GRANT"  
    login_unix_socket: /var/run/mysql/mysql.sock
    login_user: root
    login_password: ""
